apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-service-deployment
spec:
  selector:
    matchLabels:
      app: openai-service
      environment: production
      tier: backend
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: peerprep
  template:
    metadata:
      labels:
        app: openai-service
        environment: production
        tier: backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: peerprep
      annotations:
        commit: 7322af717ee4ae86491c0105077936e77c6fb022
    spec:
      containers:
        - name: openai-service-backend
          image: asia-southeast1-docker.pkg.dev/cs3219-402913/peerprep/openaiservice_prod:latest
          ports:
            - containerPort: 3005
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-service-secrets
                  key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: openai-service-load-balancer
spec:
  selector:
    app: openai-service
    environment: production
    tier: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: peerprep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: LoadBalancer
