const OK_STATUS_CODE = 200;
const BAD_REQUEST_STATUS_CODE = 400;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;

const SALT_ROUNDS = 10;

export {
  OK_STATUS_CODE,
  BAD_REQUEST_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
  SALT_ROUNDS
};
