FROM node:18
WORKDIR /userservice
COPY package*.json ./
RUN npm i
COPY app.ts ./
COPY tsconfig.json ./
WORKDIR /userservice/src
COPY src ./
EXPOSE 3000
RUN npm run build
CMD ["npm", "run", "start:prod"]