apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service-deployment
spec:
  selector:
    matchLabels:
      app: question-service
      environment: production
      tier: backend
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: peerprep
  template:
    metadata:
      labels:
        app: question-service
        environment: production
        tier: backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: peerprep
      annotations:
        commit: 7322af717ee4ae86491c0105077936e77c6fb022
    spec:
      containers:
        - name: question-service-backend
          image: asia-southeast1-docker.pkg.dev/cs3219-402913/peerprep/questionservice_prod:latest
          ports:
            - containerPort: 3001
          env:
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: endpoints
                  key: user-service

            - name: MATCHING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: endpoints
                  key: matching-service
