name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Use v2 of the action

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Create env file for user service
        run: echo -e "${{ secrets.USER_SERVICE_ENV_FILE }}" > ./user-service/.env

      - name: Create env file for matching service
        run: echo -e "${{ secrets.MATCHING_SERVICE_ENV_FILE }}" > ./matching-service/.env

      - name: Create env file for collaboration service
        run: echo -e "${{ secrets.COLLABORATION_SERVICE_ENV_FILE }}" > ./collaboration-service/.env

      - name: Build and test client
        working-directory: ./client
        run: |
          npm install
          npm test
      
      - name: Build and test question-service
        working-directory: ./question-service
        run: |
          npm install
          npm test
            
      # - name: Build Docker containers
      #   run: docker-compose -f docker-compose.yml build

      # - name: Push Docker containers to Docker Hub
      #   run: docker-compose -f docker-compose.yml push

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to AWS Elastic Beanstalk 
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-docker
      #     environment_name: Multi-docker-env
      #     existing_bucket_name: elasticbeanstalk-ap-southeast-1-332848504892
      #     region: ap-southeast-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
